### ISSUE TITLE
IP regexp from yiisoft/validator

### ISSUE THREAD

**Issue by kamarton** [yiisoft/network-utilities#5]
I suggest moving the IP regex from the  `yiisoft/validator` package here to the `IpHelper` class as a public constant.

https://github.com/yiisoft/validator/blob/725fdfc3c18d8ef0fee3ed80fd73abe417620d77/src/Rule/Ip.php#L105-L112

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by kamarton** [comment]
Now I see that this regexp is even used in JavaScript. Depending on the #4 issue, it is not necessary because the validation will already be performed by the `inet_pton ()` function on the PHP page.

**Comment by samdark** [comment]
#4 is now solved.
